version: 2

sources:
  - name: gz_raw_data
    
    tables: 
      - name: raw_gz_sales
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

        tests:
         - unique: 
              column_name: "(orders_id||'_'||pdt_id)"
        description: sales of Greenweez / we have on row per product_id found in each orders_id

        
        columns:
          - name: date_date
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity          
                
      - name: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            tests:
              - not_null
              - unique 
          - name: purchSE_PRICE
                      
      - name: raw_gz_ship
        description: decrit les livraisons de produits Greenweez
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
          - name: shipping_fee
          - name: shipping_fee_1
          - name: logCost
          - name: ship_cost

      - name: raw_gz_adwords
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click
      
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
          - name: paid_source
          - name: campaign_key
          - name: camPGN_name
          - name: ads_cost
          - name: impression
          - name: click

    
    
models: 
  - name: int_orders_margin
    description: marge commandes
    columns:
      - name: orders_id
        tests: 
          - unique
          - not_null

  - name: int_orders_operational
    description: marge opérationelle
    columns:
      - name: orders_id
        tests: 
          - unique
          - not_null

  - name: finance_days
    description: marge opérationelle
    columns:
      - name: date_date
        tests: 
          - unique
          - not_null
          
          